"""Domain entities for depth-graph-search.

All types in this module are pure stdlib — ZERO external dependencies.
Do not import anything outside of Python's standard library here.
This is a non-negotiable Clean Architecture constraint: the domain layer
must be importable without any pip installs.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, TypeAlias
from uuid import uuid4

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

Metadata: TypeAlias = dict[str, Any]
"""Free-form key-value pairs with no fixed schema. Any JSON-serializable dict is valid."""


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Embedding:
    """A dense vector representation of a piece of text.

    Attributes:
        vector: The raw float vector. No numpy dependency — adapters convert at their boundary.
        model: Model identifier used to generate this embedding (e.g. "text-embedding-3-small").
        dimensions: Number of elements in ``vector``. MUST equal ``len(vector)``.
    """

    vector: list[float]
    model: str
    dimensions: int


@dataclass(frozen=True)
class Node:
    """An immutable domain node in the knowledge graph.

    IDs are generated by the domain (uuid4) — NOT by the database. A ``Node``
    is a complete, valid entity the moment it is constructed, before any
    adapter persists it.

    Attributes:
        content: The text content of this node. Required; must be non-empty.
        id: UUID4 string auto-generated at construction. Override only in tests or
            when re-hydrating a persisted node.
        embedding: Dense vector representation. ``None`` until the embed step runs.
            Adapters MUST validate non-``None`` before persistence.
        metadata: Free-form key-value pairs. Defaults to empty dict.
    """

    content: str
    id: str = field(default_factory=lambda: str(uuid4()))
    embedding: Embedding | None = None
    metadata: Metadata = field(default_factory=dict)


@dataclass(frozen=True)
class Edge:
    """An immutable directed relationship between two nodes.

    No ``metadata`` field in v0.1 — kept intentionally minimal.

    Attributes:
        source_id: ID of the source ``Node``.
        target_id: ID of the target ``Node``.
        relationship: Free-form relationship label (e.g. ``"CAUSES"``, ``"PART_OF"``).
        id: UUID4 string auto-generated at construction.
    """

    source_id: str
    target_id: str
    relationship: str
    id: str = field(default_factory=lambda: str(uuid4()))


@dataclass(frozen=True)
class ScoredNode:
    """A node ranked by its relevance to a search query.

    Callers are responsible for ordering: score descending, distance ascending.

    Attributes:
        node: The ranked node.
        score: Hybrid similarity score in [0, 1]. Higher means more relevant.
        distance: BFS hops from the nearest entry node. 0 means the node itself
            was an entry point.
    """

    node: Node
    score: float
    distance: int


@dataclass(frozen=True)
class ResolvedNode:
    """The result of entity resolution for a single candidate node.

    Attributes:
        node: The candidate node being resolved.
        is_new: ``True`` if no existing node matched above the similarity threshold;
            ``False`` if the node was matched to an existing one.
        matched_id: The existing node's ID when ``is_new=False``; ``None`` when new.
    """

    node: Node
    is_new: bool
    matched_id: str | None = None


@dataclass(frozen=True)
class IngestionResult:
    """Result summary of an ingestion pipeline run.

    A domain value object returned by ``IngestionPipeline.ingest()``. Reusable
    across SDK, API, and CLI layers — it carries only counts, never raw data.

    Attributes:
        node_count: Number of new nodes persisted to the graph store.
        edge_count: Number of edges persisted to the graph store (all rewired edges).
    """

    node_count: int
    edge_count: int
